title: "KMDocs"
description: "Team documentation and work notes"
baseurl: ""  # KOSONGIN kalau repo namanya username.github.io
url: "https://ern-sys.github.io"

# KALAU repo namanya KMDocs, pake ini:
baseurl: "/KMDocs"
url: "https://ern-sys.github.io"

markdown: kramdown
highlighter: rouge

permalink: pretty

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

# PASTIKAN include assets
include:
  - _layouts
  - _includes
  - assets

# Explicit exclude yang gak perlu
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor