title: "KMDocs"
description: "Team documentation and work notes"
baseurl: "/KMDocs"
url: "https://yourusername.github.io"
theme: null  # We're using custom CSS

markdown: kramdown
highlighter: rouge

sass:
  sass_dir: assets/css

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

collections:
  docs:
    output: true
    permalink: /docs/:path/

plugins:
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled: true
  collections: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules