site_name: "KMDocs"
site_description: "Knowledge Management Docs - KMDocs"
repo_url: https://github.com/ern-sys/KMDocs
repo_name: ern-sys/KMDocs
edit_uri: edit/main/docs/

nav:
nav:
  - Home: index.md
  - Cabling: cabling.md
  - Network: network.md
  - Monitoring: monitoring.md
  - Security: security.md
  - Problem Solving:
      - Firewall: firewall.md
      - DNS Issues: dns.md


theme:
  name: material
  language: 'id'

plugins:
  - search
