site_name: "KMDocs"
site_description: "Knowledge Management Docs - KMDocs"
repo_url: https://github.com/ern-sys/KMDocs
repo_name: ern-sys/KMDocs
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Cabling: cabling.md
  - Network: network.md
  - Server: proxmox.md
  - Virtualization: virtualization.md
  - Storage: storage.md
  - Backup: backup.md
  - Monitoring: monitoring.md
  - Security: security.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md
  - About: about.md

theme:
  name: material
  language: 'id'

plugins:
  - search
